### PR TITLE
feat: discord link

### PR DESCRIPTION
**Pull request by SrIzan10**
redirects you to a discord invite link so you don't need to renember the code!

### CODE REVIEW

**Review by Murtatrxx — APPROVED** [review]
Looks good.

**Comment by jacoobes** [comment]
this should be in static/ so docusaurus can read it

**Comment by SrIzan10** [comment]
OHHHH

**Comment by SrIzan10** [comment]
by moving discord.html to static, you can use https://sern-handler.js.org/discord right?

**Comment by jacoobes** [comment]
yes, but if you provide a path instead of a link, your browser does not make a new tab

**Comment by SrIzan10** [comment]
🎉

**Pull request merged**
