### PR TITLE
fix: hand lers. rede fined.

### PR DESCRIPTION
**Pull request by SrIzan10**

### CODE REVIEW

**Comment by Murtatrxx** [comment]
😨 fix was easy

**Comment by SrIzan10** [comment]
dont merge

**Comment by Murtatrxx** [comment]
Ok but why

**Review by Murtatrxx — APPROVED** [review]

**Comment by SrIzan10** [comment]
it's still not fixed on my end

(iPhone 5 yes ik its old)

**Comment by SrIzan10** [comment]
kay done

**Review by Murtatrxx — APPROVED** [review]

**Comment by SrIzan10** [comment]
🎉

**Pull request merged**
