### PR TITLE
fix: hero image stretched out

### PR DESCRIPTION
**Pull request by SrIzan10**
This SHOULD fix it.

Didn’t test, so revert if it doesn’t work please

### CODE REVIEW

**Review by Murtatrxx — COMMENTED** [review]
I'll test these changes and then approve

**Comment by SrIzan10** [comment]
Thank you!
I’m on vacation, so I can’t test it hehe

**Comment by SrIzan10** [comment]
Any thoughts of hosting in Vercel? It has previews on PRs

**Comment by Murtatrxx** [comment]
We are already using netlify to build website, but I can't check it rn

**Comment by SrIzan10** [comment]
Hey!
Did the testing work?
Sorry for being impatient, this comment is for keeping my collaboration streak on GitHub

**Comment by jacoobes** [comment]
Will try to check it out today, don't know why netlify did not display test deploy

**Comment by jacoobes** [comment]
Locally, my iphone simulator looks okay. Had to fix a quick bug.

**Review by jacoobes — APPROVED** [review]

**Comment by jacoobes** [comment]
cheers

**Review by Murtatrxx — APPROVED** [review]

**Pull request merged**
