### PR TITLE
feat: plugin page

### LINKED ISSUE #61: Finish plugins page
https://sern.dev/plugins

- This has been on todo for a while
- Plan is to get a copy of this [json](https://github.com/sern-handler/awesome-plugins/blob/main/pluginlist.json) file while bundling and display it accordingly.

### PR DESCRIPTION
**Pull request by SrIzan10**
hallo

this adds a very cool feature, and everyone was waiting for it  
k bye

closes #61

### CODE REVIEW

**Comment by jacoobes** [comment]
Looking good! can you truncate it to x characters so that all the cards are even?

**Comment by SrIzan10** [comment]
yeah, how many?
I could also order by description character length

**Comment by jacoobes** [comment]
100 chars, and nah thats not needed

**Comment by SrIzan10** [comment]
ready to merge!

**Comment by jacoobes** [comment]
AWESOME!

**Pull request merged**
