### PR TITLE
feat: version 3

### PR DESCRIPTION
**Pull request by jacoobes**

### CODE REVIEW

**Comment by Murtatrxx** [comment]
Okay looks fine, we can attach new logo before the release. So it won’t be leaked.

**Review by Murtatrxx — APPROVED** [review]

**Comment by jacoobes** [comment]
waiting on automated documentation generation, its either a bug on typedocs end or my end, still havent figured

**Comment by jacoobes** [comment]
alright heres whats up
- [x] docs
- [x] integrate new logo
- [x] integrate the color scheme
- [x] blog

**Review by SrIzan10 — APPROVED** [review]
lgtm

**Pull request merged**
